language: node_js
node_js:
    - "7.5"
    - "10.15"
services:
    - mongodb
env:
  global:
    - NODE_ENV=test
after_success: npm run coverage
cache:
  directories:
    - node_modules
deploy:
  provider: heroku
  app: the-movie-box-service
  api_key:
    secure: c427b03f-663f-4ad2-9919-d870160f45cf